package workspace

import (
	"bytes"
	"os"
	"path/filepath"
	"sync"
	"testing"
)

func TestWorkspaceSharesSourceAndCST(t *testing.T) {
	root := t.TempDir()
	filename := filepath.Join(root, "main.go")
	original := []byte("package p\nfunc F() {}\n")
	if err := os.WriteFile(filename, original, 0o600); err != nil {
		t.Fatal(err)
	}
	opened, err := Open([]string{root}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	files := opened.Files()
	if len(files) != 1 || files[0].Path() != filename {
		t.Fatalf("unexpected files: %#v", files)
	}

	var group sync.WaitGroup
	trees := make(chan any, 16)
	for range 16 {
		group.Add(1)
		go func() {
			defer group.Done()
			tree, treeErr := files[0].CST()
			if treeErr != nil {
				t.Errorf("CST: %v", treeErr)
				return
			}
			trees <- tree
		}()
	}
	group.Wait()
	close(trees)
	var first any
	for tree := range trees {
		if first == nil {
			first = tree
		}
		if tree != first {
			t.Fatal("CST was not shared")
		}
	}

	if err := os.WriteFile(filename, []byte("package changed\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	contents, err := files[0].Bytes()
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != string(original) {
		t.Fatalf("cached source changed: %q", contents)
	}
}

func TestWorkspaceFiltersGeneratedAndExcludedFiles(t *testing.T) {
	root := t.TempDir()
	for name, contents := range map[string]string{"keep.go": "package p\n", "skip.go": "package p\n", "generated.go": "// Code generated by test. DO NOT EDIT.\npackage p\n"} {
		if err := os.WriteFile(filepath.Join(root, name), []byte(contents), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	opened, err := Open([]string{root}, Options{SkipGenerated: true, Root: root, Excludes: []string{"skip.go"}})
	if err != nil {
		t.Fatal(err)
	}
	files := opened.Files()
	if len(files) != 1 || filepath.Base(files[0].Path()) != "keep.go" {
		t.Fatalf("unexpected files: %#v", files)
	}
}

func TestReleaseCSTDropsImmutableGenerationCache(t *testing.T) {
	directory := t.TempDir()
	filename := filepath.Join(directory, "main.go")
	if err := os.WriteFile(filename, []byte("package main\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	shared, err := Open([]string{filename}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	file := shared.Files()[0]
	if _, err := file.CST(); err != nil {
		t.Fatal(err)
	}
	file.ReleaseCST()
	if _, err := file.CST(); err == nil {
		t.Fatal("released CST was unexpectedly reusable")
	}
	if contents, err := file.Bytes(); err != nil || string(contents) != "package main\n" {
		t.Fatalf("source cache after CST release = %q, %v", contents, err)
	}
}

func TestCacheReusesImmutableSnapshotAcrossGenerations(t *testing.T) {
	directory := t.TempDir()
	filename := filepath.Join(directory, "main.go")
	original := []byte("package main\nfunc main() {}\n")
	if err := os.WriteFile(filename, original, 0o600); err != nil {
		t.Fatal(err)
	}
	cache := NewCache(CacheOptions{MaxEntries: 4, MaxBytes: 1 << 20})
	first, err := cache.Open([]string{directory}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	firstFile := first.Files()[0]
	firstIdentity, err := firstFile.Identity()
	if err != nil {
		t.Fatal(err)
	}
	firstTree, err := firstFile.CST()
	if err != nil {
		t.Fatal(err)
	}
	firstFile.Release()

	second, err := cache.Open([]string{directory}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	secondFile := second.Files()[0]
	secondIdentity, err := secondFile.Identity()
	if err != nil {
		t.Fatal(err)
	}
	secondTree, err := secondFile.CST()
	if err != nil {
		t.Fatal(err)
	}
	if first.Generation() != 1 || second.Generation() != 2 {
		t.Fatalf("generations = %d, %d", first.Generation(), second.Generation())
	}
	if firstFile == secondFile {
		t.Fatal("workspace generations shared a releasable File handle")
	}
	if firstIdentity != secondIdentity || firstTree != secondTree {
		t.Fatal("unchanged source snapshot or CST was not reused")
	}
	stats := cache.Stats()
	if stats.Hits != 1 || stats.Misses != 1 || stats.Entries != 1 {
		t.Fatalf("unexpected cache stats: %#v", stats)
	}
}

func TestCacheContentIdentityInvalidatesSameSizeSource(t *testing.T) {
	directory := t.TempDir()
	filename := filepath.Join(directory, "main.go")
	if err := os.WriteFile(filename, []byte("package one\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	cache := NewCache(CacheOptions{MaxEntries: 4, MaxBytes: 1 << 20})
	first, err := cache.Open([]string{filename}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	firstIdentity, err := first.Files()[0].Identity()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filename, []byte("package two\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	second, err := cache.Open([]string{filename}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	secondIdentity, err := second.Files()[0].Identity()
	if err != nil {
		t.Fatal(err)
	}
	if firstIdentity == secondIdentity {
		t.Fatal("same-size content mutation retained the old identity")
	}
	firstSource, err := first.Files()[0].Bytes()
	if err != nil {
		t.Fatal(err)
	}
	secondSource, err := second.Files()[0].Bytes()
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(firstSource, []byte("package one\n")) || !bytes.Equal(secondSource, []byte("package two\n")) {
		t.Fatalf("mixed generations: first %q, second %q", firstSource, secondSource)
	}
}

func TestCacheDeterministicallyEvictsLeastRecentlyUsedSnapshot(t *testing.T) {
	directory := t.TempDir()
	for _, name := range[]string{"a.go", "b.go", "c.go"} {
		if err := os.WriteFile(filepath.Join(directory, name), []byte("package p\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	cache := NewCache(CacheOptions{MaxEntries: 2, MaxBytes: 1 << 20})
	if _, err := cache.Open([]string{directory}, Options{}); err != nil {
		t.Fatal(err)
	}
	stats := cache.Stats()
	if stats.Entries != 2 || stats.Evictions != 1 {
		t.Fatalf("unexpected first-generation stats: %#v", stats)
	}
	if _, err := cache.Open([]string{filepath.Join(directory, "c.go")}, Options{}); err != nil {
		t.Fatal(err)
	}
	afterC := cache.Stats()
	if afterC.Hits != stats.Hits + 1 {
		t.Fatalf("lexically last retained entry missed: before %#v, after %#v", stats, afterC)
	}
	if _, err := cache.Open([]string{filepath.Join(directory, "a.go")}, Options{}); err != nil {
		t.Fatal(err)
	}
	afterA := cache.Stats()
	if afterA.Misses != afterC.Misses + 1 || afterA.Entries != 2 {
		t.Fatalf("least-recently-used entry was not evicted: %#v", afterA)
	}
}

func TestCacheBoundsRetainedSourceBytes(t *testing.T) {
	directory := t.TempDir()
	filename := filepath.Join(directory, "large.go")
	contents := []byte("package p\n// source larger than the cache budget\n")
	if err := os.WriteFile(filename, contents, 0o600); err != nil {
		t.Fatal(err)
	}
	cache := NewCache(CacheOptions{MaxEntries: 4, MaxBytes: int64(len(contents) - 1)})
	opened, err := cache.Open([]string{filename}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if got, readErr := opened.Files()[0].Bytes(); readErr != nil || !bytes.Equal(got, contents) {
		t.Fatalf("generation source = %q, %v", got, readErr)
	}
	stats := cache.Stats()
	if stats.Entries != 0 || stats.Bytes != 0 {
		t.Fatalf("oversized snapshot was retained: %#v", stats)
	}
}

func TestCacheBoundsEstimatedCSTBytes(t *testing.T) {
	directory := t.TempDir()
	filename := filepath.Join(directory, "main.go")
	if err := os.WriteFile(filename, []byte("package main\nfunc main() {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	cache := NewCache(CacheOptions{MaxEntries: 4, MaxBytes: 1 << 20, MaxTreeBytes: 1})
	opened, err := cache.Open([]string{filename}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	file := opened.Files()[0]
	first, err := file.CST()
	if err != nil {
		t.Fatal(err)
	}
	second, err := file.CST()
	if err != nil || first != second {
		t.Fatalf("live generation lost its evicted CST: %p, %p, %v", first, second, err)
	}
	stats := cache.Stats()
	if stats.Entries != 0 || stats.TreeBytes != 0 || stats.Evictions != 1 {
		t.Fatalf("oversized CST estimate was retained: %#v", stats)
	}
	if _, err := cache.Open([]string{filename}, Options{}); err != nil {
		t.Fatal(err)
	}
	if stats := cache.Stats(); stats.Misses != 2 {
		t.Fatalf("evicted CST snapshot was unexpectedly reused: %#v", stats)
	}
}

func TestCacheConcurrentOpenPublishesDistinctGenerations(t *testing.T) {
	directory := t.TempDir()
	filename := filepath.Join(directory, "main.go")
	if err := os.WriteFile(filename, []byte("package main\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	cache := NewCache(CacheOptions{MaxEntries: 8, MaxBytes: 1 << 20})
	generations := make(chan uint64, 16)
	errors := make(chan error, 16)
	var group sync.WaitGroup
	for range 16 {
		group.Add(1)
		go func() {
			defer group.Done()
			opened, err := cache.Open([]string{filename}, Options{})
			if err != nil {
				errors <- err
				return
			}
			if _, err := opened.Files()[0].CST(); err != nil {
				errors <- err
				return
			}
			generations <- opened.Generation()
		}()
	}
	group.Wait()
	close(errors)
	for err := range errors {
		t.Error(err)
	}
	close(generations)
	seen := make(map[uint64]bool)
	for generation := range generations {
		if seen[generation] {
			t.Fatalf("duplicate generation %d", generation)
		}
		seen[generation] = true
	}
	if len(seen) != 16 {
		t.Fatalf("published %d generations, want 16", len(seen))
	}
	stats := cache.Stats()
	if stats.Hits != 15 || stats.Misses != 1 {
		t.Fatalf("unexpected concurrent cache stats: %#v", stats)
	}
}

func BenchmarkCacheUnchangedGeneration(benchmark *testing.B) {
	directory := benchmark.TempDir()
	filename := filepath.Join(directory, "main.go")
	if err := os.WriteFile(filename, []byte("package main\nfunc main() { println(\"hello\") }\n"), 0o600); err != nil {
		benchmark.Fatal(err)
	}
	cache := NewCache(CacheOptions{MaxEntries: 8, MaxBytes: 1 << 20})
	first, err := cache.Open([]string{filename}, Options{})
	if err != nil {
		benchmark.Fatal(err)
	}
	if _, err := first.Files()[0].CST(); err != nil {
		benchmark.Fatal(err)
	}
	benchmark.ReportAllocs()
	benchmark.ResetTimer()
	for range benchmark.N {
		opened, err := cache.Open([]string{filename}, Options{})
		if err != nil {
			benchmark.Fatal(err)
		}
		if _, err := opened.Files()[0].CST(); err != nil {
			benchmark.Fatal(err)
		}
	}
}
