package source

import (
	"os"
	"path/filepath"
	"slices"
	"testing"
)

func TestDiscoverSkipsGeneratedAndVendor(t *testing.T) {
	root := t.TempDir()
	write := func(name, content string) string {
		t.Helper()
		filename := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(filename), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filename, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		absolute, err := filepath.Abs(filename)
		if err != nil {
			t.Fatal(err)
		}
		return absolute
	}
	wanted := write("main.go", "package main\n")
	write("generated.go", "// Code generated by test. DO NOT EDIT.\npackage main\n")
	write("vendor/dependency.go", "package vendor\n")
	write(".cache/cached.go", "package cache\n")
	write("_scratch/scratch.go", "package scratch\n")
	write("notes.txt", "not go")
	files, err := Discover(
		[]string{root + string(filepath.Separator) + "..."},
		Options{SkipGenerated: true},
	)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(files, []string{wanted}) {
		t.Fatalf("got %v, want %v", files, []string{wanted})
	}
}

func TestDiscoverAllowsExplicitHiddenDirectory(t *testing.T) {
	root := t.TempDir()
	hidden := filepath.Join(root, ".source")
	if err := os.MkdirAll(hidden, 0o755); err != nil {
		t.Fatal(err)
	}
	filename := filepath.Join(hidden, "main.go")
	if err := os.WriteFile(filename, []byte("package main\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	files, err := Discover([]string{hidden}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	absolute, err := filepath.Abs(filename)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(files, []string{absolute}) {
		t.Fatalf("got %v, want explicit hidden source %s", files, absolute)
	}
}
