package source

import (
	"os"
	"path/filepath"
	"slices"
	"testing"
)

func TestDiscoverSkipsGeneratedAndVendor(t *testing.T) {
	root := t.TempDir()
	write := func(name, content string) string {
		t.Helper()
		filename := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(filename), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filename, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		absolute, _ := filepath.Abs(filename)
		return absolute
	}
	wanted := write("main.go", "package main\n")
	write("generated.go", "// Code generated by test. DO NOT EDIT.\npackage main\n")
	write("vendor/dependency.go", "package vendor\n")
	write("notes.txt", "not go")

	files, err := Discover([]string{root + string(filepath.Separator) + "..."}, Options{SkipGenerated: true})
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(files, []string{wanted}) {
		t.Fatalf("got %v, want %v", files, []string{wanted})
	}
}
