// Command gencst generates direct modernc CST child accessors for Strider.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const parserPackage = "modernc.org/gc/v3"

type nodeType struct {
	name    string
	value   bool
	pointer bool
	fields  []nodeField
}

type nodeField struct {
	name     string
	typeName string
	kind     fieldKind
}

type fieldKind uint8

const (
	fieldOpaque fieldKind = iota
	fieldToken
	fieldPointer
	fieldInterface
	fieldSlice
	fieldTokenPointer
)

func main() {
	output := flag.String("output", "zz_nodes_generated.go", "generated file path")
	check := flag.Bool("check", false, "check that the generated file is current")
	flag.Parse()

	generated, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, "generate CST accessors:", err)
		os.Exit(1)
	}
	if *check {
		current, readErr := os.ReadFile(*output)
		if readErr != nil {
			fmt.Fprintln(os.Stderr, "check generated CST accessors:", readErr)
			os.Exit(1)
		}
		if !bytes.Equal(current, generated) {
			fmt.Fprintf(os.Stderr, "%s is stale; run go generate ./internal/cst\n", *output)
			os.Exit(1)
		}
		return
	}
	if current, err := os.ReadFile(*output); err == nil && bytes.Equal(current, generated) {
		return
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write generated CST accessors:", err)
		os.Exit(1)
	}
}

func generate() ([]byte, error) {
	configuration := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesSizes | packages.NeedModule,
	}
	loaded, err := packages.Load(configuration, parserPackage)
	if err != nil {
		return nil, err
	}
	if len(loaded) != 1 {
		return nil, fmt.Errorf("loaded %d packages for %s", len(loaded), parserPackage)
	}
	if len(loaded[0].Errors) != 0 {
		return nil, loaded[0].Errors[0]
	}

	pkg := loaded[0].Types
	nodeObject, ok := pkg.Scope().Lookup("Node").(*types.TypeName)
	if !ok {
		return nil, fmt.Errorf("%s.Node is not a named interface", parserPackage)
	}
	nodeInterface, ok := nodeObject.Type().Underlying().(*types.Interface)
	if !ok {
		return nil, fmt.Errorf("%s.Node is not an interface", parserPackage)
	}
	nodeInterface.Complete()
	tokenObject, ok := pkg.Scope().Lookup("Token").(*types.TypeName)
	if !ok {
		return nil, fmt.Errorf("%s.Token is not a named type", parserPackage)
	}

	nodes, schema, err := discoverNodes(pkg, nodeInterface, tokenObject.Type())
	if err != nil {
		return nil, err
	}
	digest := sha256.Sum256([]byte(schema))
	version := "unknown"
	if loaded[0].Module != nil && loaded[0].Module.Version != "" {
		version = loaded[0].Module.Version
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintf(&output, "// modernc.org/gc/v3 %s node schema: %x\n\n", version, digest)
	fmt.Fprintln(&output, "package cst")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "import gc \"modernc.org/gc/v3\"")
	fmt.Fprintln(&output)
	emitNodePresent(&output, nodes)
	emitNodeNil(&output, nodes)
	emitKind(&output, nodes)
	emitChildren(&output, nodes, false)
	emitChildren(&output, nodes, true)
	emitTokenItems(&output, nodes)

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func discoverNodes(pkg *types.Package, nodeInterface *types.Interface, tokenType types.Type) ([]nodeType, string, error) {
	names := pkg.Scope().Names()
	sort.Strings(names)
	nodes := make([]nodeType, 0, len(names))
	var schema strings.Builder
	for _, name := range names {
		object, ok := pkg.Scope().Lookup(name).(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := types.Unalias(object.Type()).(*types.Named)
		if !ok {
			continue
		}
		structure, ok := named.Underlying().(*types.Struct)
		if !ok {
			continue
		}
		valueImplementation := types.Implements(named, nodeInterface)
		pointerImplementation := types.Implements(types.NewPointer(named), nodeInterface)
		if !valueImplementation && !pointerImplementation {
			continue
		}
		if !object.Exported() {
			// modernc uses an unexported, empty nonode sentinel while checking
			// semantic types. It is not reachable from ParseFile's CST. Any new
			// unexported implementation must be reviewed rather than omitted.
			if name != "nonode" || structure.NumFields() != 0 {
				return nil, "", fmt.Errorf("unnameable Node implementation %s.%s", pkg.Path(), name)
			}
			fmt.Fprintf(&schema, "unexported:%s:value=%t:pointer=%t\n", name, valueImplementation, pointerImplementation)
			continue
		}

		current := nodeType{
			name:    name,
			value:   valueImplementation,
			pointer: pointerImplementation,
		}
		fmt.Fprintf(&schema, "type:%s:value=%t:pointer=%t\n", name, valueImplementation, pointerImplementation)
		for index := 0; index < structure.NumFields(); index++ {
			field := structure.Field(index)
			if !field.Exported() {
				continue
			}
			kind := classifyField(field.Type(), nodeInterface, tokenType)
			typeName := types.TypeString(field.Type(), func(imported *types.Package) string {
				if imported.Path() == parserPackage {
					return "gc"
				}
				return imported.Name()
			})
			current.fields = append(current.fields, nodeField{
				name:     field.Name(),
				typeName: typeName,
				kind:     kind,
			})
			fmt.Fprintf(&schema, "field:%s:%s:%d\n", field.Name(), typeName, kind)
			if kind == fieldOpaque && containsNode(field.Type(), nodeInterface, map[types.Type]bool{}) {
				return nil, "", fmt.Errorf("unsupported Node-containing field %s.%s (%s)", name, field.Name(), typeName)
			}
		}
		nodes = append(nodes, current)
	}
	return nodes, schema.String(), nil
}

func classifyField(fieldType types.Type, nodeInterface *types.Interface, tokenType types.Type) fieldKind {
	if types.Identical(fieldType, tokenType) {
		return fieldToken
	}
	if pointer, ok := fieldType.(*types.Pointer); ok && types.Identical(pointer.Elem(), tokenType) {
		return fieldTokenPointer
	}
	if slice, ok := fieldType.(*types.Slice); ok && types.Implements(slice.Elem(), nodeInterface) {
		return fieldSlice
	}
	if !types.Implements(fieldType, nodeInterface) {
		return fieldOpaque
	}
	if _, ok := fieldType.(*types.Pointer); ok {
		return fieldPointer
	}
	if _, ok := fieldType.Underlying().(*types.Interface); ok {
		return fieldInterface
	}
	return fieldInterface
}

func containsNode(current types.Type, nodeInterface *types.Interface, seen map[types.Type]bool) bool {
	if current == nil || seen[current] {
		return false
	}
	seen[current] = true
	if types.Implements(current, nodeInterface) {
		return true
	}
	switch value := current.Underlying().(type) {
	case *types.Pointer:
		return containsNode(value.Elem(), nodeInterface, seen)
	case *types.Array:
		return containsNode(value.Elem(), nodeInterface, seen)
	case *types.Slice:
		return containsNode(value.Elem(), nodeInterface, seen)
	case *types.Interface:
		// Reflection can observe a Node stored in a broad interface such as
		// any even though the interface itself does not implement Node. Make
		// dependency upgrades review and explicitly support that shape.
		return true
	case *types.Struct:
		for index := 0; index < value.NumFields(); index++ {
			if value.Field(index).Exported() && containsNode(value.Field(index).Type(), nodeInterface, seen) {
				return true
			}
		}
	}
	return false
}

func emitNodePresent(output *bytes.Buffer, nodes []nodeType) {
	fmt.Fprintln(output, "func generatedNodePresent(node Node) (bool, bool) {")
	fmt.Fprintln(output, "\tswitch current := node.(type) {")
	fmt.Fprintln(output, "\tcase nil:")
	fmt.Fprintln(output, "\t\treturn false, true")
	for _, current := range nodes {
		if current.value {
			fmt.Fprintf(output, "\tcase gc.%s:\n", current.name)
			if current.name == "Token" {
				fmt.Fprintln(output, "\t\treturn current.IsValid(), true")
			} else {
				fmt.Fprintln(output, "\t\treturn true, true")
			}
		}
		if current.pointer {
			fmt.Fprintf(output, "\tcase *gc.%s:\n", current.name)
			fmt.Fprintln(output, "\t\treturn current != nil, true")
		}
	}
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn false, false")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func emitNodeNil(output *bytes.Buffer, nodes []nodeType) {
	fmt.Fprintln(output, "func generatedNodeNil(node Node) (bool, bool) {")
	fmt.Fprintln(output, "\tswitch current := node.(type) {")
	fmt.Fprintln(output, "\tcase nil:")
	fmt.Fprintln(output, "\t\treturn true, true")
	for _, current := range nodes {
		if current.value {
			fmt.Fprintf(output, "\tcase gc.%s:\n", current.name)
			fmt.Fprintln(output, "\t\treturn false, true")
		}
		if current.pointer {
			fmt.Fprintf(output, "\tcase *gc.%s:\n", current.name)
			fmt.Fprintln(output, "\t\treturn current == nil, true")
		}
	}
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn false, false")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func emitKind(output *bytes.Buffer, nodes []nodeType) {
	fmt.Fprintln(output, "func generatedKind(node Node) (string, bool) {")
	fmt.Fprintln(output, "\tswitch node.(type) {")
	for _, current := range nodes {
		cases := make([]string, 0, 2)
		if current.value {
			cases = append(cases, "gc."+current.name)
		}
		if current.pointer {
			cases = append(cases, "*gc."+current.name)
		}
		fmt.Fprintf(output, "\tcase %s:\n", strings.Join(cases, ", "))
		fmt.Fprintf(output, "\t\treturn %q, true\n", strings.TrimSuffix(current.name, "Node"))
	}
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn \"\", false")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func emitChildren(output *bytes.Buffer, nodes []nodeType, items bool) {
	if items {
		fmt.Fprintln(output, "func appendGeneratedChildItemsReverse[T ~struct {")
		fmt.Fprintln(output, "\tnode Node")
		fmt.Fprintln(output, "\texit bool")
		fmt.Fprintln(output, "}](stack []T, node Node, includeTokens bool) ([]T, bool) {")
	} else {
		fmt.Fprintln(output, "func appendGeneratedChildren(stack []Node, node Node, reverse bool) ([]Node, bool) {")
	}
	fmt.Fprintln(output, "\tswitch current := node.(type) {")
	for _, current := range nodes {
		if current.value {
			fmt.Fprintf(output, "\tcase gc.%s:\n", current.name)
			emitFields(output, current.fields, items)
			fmt.Fprintln(output, "\t\treturn stack, true")
		}
		if current.pointer {
			fmt.Fprintf(output, "\tcase *gc.%s:\n", current.name)
			fmt.Fprintln(output, "\t\tif current == nil {")
			fmt.Fprintln(output, "\t\t\treturn stack, true")
			fmt.Fprintln(output, "\t\t}")
			emitFields(output, current.fields, items)
			fmt.Fprintln(output, "\t\treturn stack, true")
		}
	}
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn stack, false")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func emitTokenItems(output *bytes.Buffer, nodes []nodeType) {
	fmt.Fprintln(output, "func appendGeneratedTokenItemsReverse(stack []tokenWalkItem, node Node) ([]tokenWalkItem, bool) {")
	fmt.Fprintln(output, "\tswitch current := node.(type) {")
	for _, current := range nodes {
		if current.value {
			fmt.Fprintf(output, "\tcase gc.%s:\n", current.name)
			for index := len(current.fields) - 1; index >= 0; index-- {
				emitTokenField(output, current.fields[index])
			}
			fmt.Fprintln(output, "\t\treturn stack, true")
		}
		if current.pointer {
			fmt.Fprintf(output, "\tcase *gc.%s:\n", current.name)
			fmt.Fprintln(output, "\t\tif current == nil {")
			fmt.Fprintln(output, "\t\t\treturn stack, true")
			fmt.Fprintln(output, "\t\t}")
			for index := len(current.fields) - 1; index >= 0; index-- {
				emitTokenField(output, current.fields[index])
			}
			fmt.Fprintln(output, "\t\treturn stack, true")
		}
	}
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn stack, false")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func emitTokenField(output *bytes.Buffer, field nodeField) {
	if field.kind == fieldOpaque {
		return
	}
	expression := "current." + field.name
	switch field.kind {
	case fieldToken:
		fmt.Fprintf(output, "\t\tif %s.IsValid() {\n", expression)
		fmt.Fprintf(output, "\t\t\tstack = append(stack, tokenWalkItem{token: %s, isToken: true})\n", expression)
		fmt.Fprintln(output, "\t\t}")
	case fieldTokenPointer:
		// A pointer to Token is a structural child for compatibility, but its
		// unexported fields do not contribute to reflection-derived bounds.
	case fieldPointer:
		fmt.Fprintf(output, "\t\tif %s != nil {\n", expression)
		fmt.Fprintf(output, "\t\t\tstack = append(stack, tokenWalkItem{node: %s})\n", expression)
		fmt.Fprintln(output, "\t\t}")
	case fieldInterface:
		fmt.Fprintf(output, "\t\tif nodePresent(%s) {\n", expression)
		fmt.Fprintf(output, "\t\t\tstack = append(stack, tokenWalkItem{node: %s})\n", expression)
		fmt.Fprintln(output, "\t\t}")
	case fieldSlice:
		fmt.Fprintf(output, "\t\tfor index := len(%s) - 1; index >= 0; index-- {\n", expression)
		fmt.Fprintf(output, "\t\t\tchild := %s[index]\n", expression)
		fmt.Fprintln(output, "\t\t\tif nodePresent(child) {")
		fmt.Fprintln(output, "\t\t\t\tstack = append(stack, tokenWalkItem{node: child})")
		fmt.Fprintln(output, "\t\t\t}")
		fmt.Fprintln(output, "\t\t}")
	}
}

func emitFields(output *bytes.Buffer, fields []nodeField, items bool) {
	if items {
		for index := len(fields) - 1; index >= 0; index-- {
			emitField(output, fields[index], true, true)
		}
		return
	}
	fmt.Fprintln(output, "\t\tif reverse {")
	for index := len(fields) - 1; index >= 0; index-- {
		emitField(output, fields[index], true, false)
	}
	fmt.Fprintln(output, "\t\t} else {")
	for _, field := range fields {
		emitField(output, field, false, false)
	}
	fmt.Fprintln(output, "\t\t}")
}

func emitField(output *bytes.Buffer, field nodeField, reverse, items bool) {
	if field.kind == fieldOpaque {
		return
	}
	expression := "current." + field.name
	appendExpression := func(value string) {
		if items {
			fmt.Fprintf(output, "\t\t\tstack = append(stack, T{node: %s})\n", value)
		} else {
			fmt.Fprintf(output, "\t\t\tstack = append(stack, %s)\n", value)
		}
	}
	switch field.kind {
	case fieldToken:
		if items {
			fmt.Fprintf(output, "\t\tif includeTokens && %s.IsValid() {\n", expression)
		} else {
			fmt.Fprintf(output, "\t\tif %s.IsValid() {\n", expression)
		}
		appendExpression(expression)
		fmt.Fprintln(output, "\t\t}")
	case fieldPointer:
		fmt.Fprintf(output, "\t\tif %s != nil {\n", expression)
		appendExpression(expression)
		fmt.Fprintln(output, "\t\t}")
	case fieldTokenPointer:
		if items {
			fmt.Fprintf(output, "\t\tif includeTokens && %s != nil {\n", expression)
		} else {
			fmt.Fprintf(output, "\t\tif %s != nil {\n", expression)
		}
		appendExpression(expression)
		fmt.Fprintln(output, "\t\t}")
	case fieldInterface:
		if items {
			fmt.Fprintf(output, "\t\tif nodePresent(%s) && (includeTokens || !tokenNode(%s)) {\n", expression, expression)
		} else {
			fmt.Fprintf(output, "\t\tif nodePresent(%s) {\n", expression)
		}
		appendExpression(expression)
		fmt.Fprintln(output, "\t\t}")
	case fieldSlice:
		if reverse {
			fmt.Fprintf(output, "\t\tfor index := len(%s) - 1; index >= 0; index-- {\n", expression)
			fmt.Fprintf(output, "\t\t\tchild := %s[index]\n", expression)
		} else {
			fmt.Fprintf(output, "\t\tfor _, child := range %s {\n", expression)
		}
		if items {
			fmt.Fprintln(output, "\t\t\tif nodePresent(child) && (includeTokens || !tokenNode(child)) {")
		} else {
			fmt.Fprintln(output, "\t\t\tif nodePresent(child) {")
		}
		if items {
			fmt.Fprintln(output, "\t\t\t\tstack = append(stack, T{node: child})")
		} else {
			fmt.Fprintln(output, "\t\t\t\tstack = append(stack, child)")
		}
		fmt.Fprintln(output, "\t\t\t}")
		fmt.Fprintln(output, "\t\t}")
	}
}
