// Command generate-check-docs renders generated syntax-check pages and keeps
// the default-severity badge on every check reference page in sync with code.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/gempir/strider/internal/checks"
	"github.com/gempir/strider/internal/checks/syntax/rules"
	"github.com/gempir/strider/internal/diagnostic"
)

const (
	generatedMarker = "<!-- Code generated by docs/scripts/generate-check-docs.go; DO NOT EDIT. -->"
	oldGeneratedMarker = "<!-- Code generated by docs/scripts/generate-lint-docs.go; DO NOT EDIT. -->"
	legacyBoilerplate = "Strider implements this rule natively in its shared lossless Go CST traversal."
	defaultSeverityPrefix = "**Default severity:**"
)

func main() {
	docsDirectory := docsDirectory()
	generateSyntaxPages(docsDirectory)
	synchronizeSeverityBadges(docsDirectory)
}

func generateSyntaxPages(docsDirectory string) {
	all, err := rules.Select(nil, true)
	if err != nil {
		fatal(err)
	}
	defaults, err := rules.Select(nil, false)
	if err != nil {
		fatal(err)
	}
	defaultCodes := make(map[string]bool, len(defaults))
	for _, rule := range defaults {
		defaultCodes[rule.Meta().Code] = true
	}
	sort.Slice(all, func(i, j int) bool {
		return all[i].Meta().Code < all[j].Meta().Code
	})

	directory := filepath.Join(docsDirectory, "lints")
	for _, rule := range all {
		meta := rule.Meta()
		if strings.TrimSpace(meta.GoodExample) == "" || strings.TrimSpace(meta.BadExample) == "" {
			fatal(fmt.Errorf("syntax check %s has incomplete examples", meta.Code))
		}
		path := filepath.Join(directory, meta.Code + ".md")
		current, readErr := os.ReadFile(path)
		if readErr != nil && !os.IsNotExist(readErr) {
			fatal(readErr)
		}
		if readErr == nil && !generatedPage(string(current)) {
			continue
		}
		content := render(
			pageData{
				code: meta.Code,
				summary: meta.Summary,
				explanation: meta.Explanation,
				bad: meta.BadExample,
				good: meta.GoodExample,
				severity: meta.DefaultSeverity,
				defaultEnabled: defaultCodes[meta.Code],
			},
		)
		if string(current) == content {
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fatal(err)
		}
	}
}

func docsDirectory() string {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal(fmt.Errorf("locate generator source"))
	}
	return filepath.Join(filepath.Dir(sourceFile), "..", "src", "content", "docs")
}

func generatedPage(contents string) bool {
	return strings.Contains(contents, generatedMarker) || strings.Contains(
		contents,
		oldGeneratedMarker,
	) || strings.Contains(contents, legacyBoilerplate)
}

type pageData struct {
	code string
	summary string
	explanation string
	bad string
	good string
	severity diagnostic.Severity
	defaultEnabled bool
}

func render(page pageData) string {
	enablement := fmt.Sprintf(
		"This optional check runs when selected with `--only %s`, enabled in `strider.toml`, or included with `--all`.",
		page.code,
	)
	if page.defaultEnabled {
		enablement = "This check is enabled in Strider's default check profile."
	}
	return fmt.Sprintf(
		`---
title: %s
description: %q
---

%s

%s %s ` + "`%s`" + `

%s

## Bad

` + "```go" + `
%s
` + "```" + `

## Good

` + "```go" + `
%s
` + "```" + `

## Enable

%s
`,
		page.code,
		prose(page.summary),
		generatedMarker,
		defaultSeverityPrefix,
		severityIcon(page.severity),
		page.severity,
		prose(page.explanation),
		strings.TrimSpace(page.bad),
		strings.TrimSpace(page.good),
		enablement,
	)
}

func synchronizeSeverityBadges(docsDirectory string) {
	registry, err := checks.NewRegistry(checks.RegistryOptions{All: true})
	if err != nil {
		fatal(err)
	}
	for _, rule := range registry.Rules() {
		meta := rule.Meta()
		path := checkPagePath(docsDirectory, meta)
		contents, readErr := os.ReadFile(path)
		if readErr != nil {
			fatal(fmt.Errorf("check %s documentation: %w", meta.Code, readErr))
		}
		updated := withSeverityBadge(string(contents), meta.DefaultSeverity)
		if updated != string(contents) {
			if writeErr := os.WriteFile(path, []byte(updated), 0o644); writeErr != nil {
				fatal(writeErr)
			}
		}
	}
}

func checkPagePath(docsDirectory string, meta checks.Meta) string {
	if meta.Code == "format" {
		return filepath.Join(docsDirectory, "formatter.md")
	}
	category := "lints"
	if meta.Capabilities & checks.CapabilityAST != 0 {
		category = "analyzers"
	}
	return filepath.Join(docsDirectory, category, meta.Code + ".md")
}

func withSeverityBadge(contents string, severity diagnostic.Severity) string {
	badge := fmt.Sprintf("%s %s `%s`", defaultSeverityPrefix, severityIcon(severity), severity)
	lines := strings.Split(contents, "\n")
	for index, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), defaultSeverityPrefix) {
			lines[index] = badge
			if index + 1 < len(lines) && strings.TrimSpace(lines[index + 1]) != "" {
				lines = append(lines[:index + 1], append([]string{""}, lines[index + 1:]...)...)
			}
			return strings.Join(lines, "\n")
		}
	}
	frontmatterEnd := -1
	for index := 1; index < len(lines); index++ {
		if strings.TrimSpace(lines[index]) == "---" {
			frontmatterEnd = index
			break
		}
	}
	if frontmatterEnd < 0 {
		fatal(fmt.Errorf("documentation page has no frontmatter"))
	}
	insertAt := frontmatterEnd + 1
	addition := []string{"", badge}
	lines = append(lines[:insertAt], append(addition, lines[insertAt:]...)...)
	return strings.Join(lines, "\n")
}

func severityIcon(severity diagnostic.Severity) string {
	switch severity {
	case diagnostic.SeverityError:
		return "🔴"
	case diagnostic.SeverityWarning:
		return "🟡"
	default:
		return "🔵"
	}
}

func prose(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return value
	}
	value = strings.ToUpper(value[:1]) + value[1:]
	if !strings.HasSuffix(value, ".") {
		value += "."
	}
	return value
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate check docs:", err)
	os.Exit(1)
}
