// Command generate-lint-docs renders the compact lint reference pages from the
// Go rule registry. Hand-written pages are preserved unless they contain the
// generated marker or the legacy boilerplate this generator replaces.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/gempir/strider/internal/lint/rules"
)

const (
	generatedMarker = "<!-- Code generated by docs/scripts/generate-lint-docs.go; DO NOT EDIT. -->"
	legacyMarker    = "Strider implements this rule natively in its shared lossless Go CST traversal."
)

func main() {
	all, err := rules.Select(nil, true)
	if err != nil {
		fatal(err)
	}
	defaults, err := rules.Select(nil, false)
	if err != nil {
		fatal(err)
	}
	defaultCodes := make(map[string]bool, len(defaults))
	for _, rule := range defaults {
		defaultCodes[rule.Meta().Code] = true
	}
	sort.Slice(all, func(i, j int) bool {
		return all[i].Meta().Code < all[j].Meta().Code
	})

	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal(fmt.Errorf("locate generator source"))
	}
	directory := filepath.Join(filepath.Dir(sourceFile), "..", "src", "content", "docs", "lints")
	for _, rule := range all {
		meta := rule.Meta()
		if strings.TrimSpace(meta.GoodExample) == "" || strings.TrimSpace(meta.BadExample) == "" {
			fatal(fmt.Errorf("lint rule %s has incomplete examples", meta.Code))
		}
		path := filepath.Join(directory, meta.Code+".md")
		current, readErr := os.ReadFile(path)
		if readErr != nil && !os.IsNotExist(readErr) {
			fatal(readErr)
		}
		if readErr == nil && !strings.Contains(string(current), generatedMarker) &&
			!strings.Contains(string(current), legacyMarker) {
			continue
		}
		content := render(
			meta.Code,
			meta.Summary,
			meta.Explanation,
			meta.BadExample,
			meta.GoodExample,
			string(meta.DefaultSeverity),
			defaultCodes[meta.Code],
		)
		if string(current) == content {
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fatal(err)
		}
	}
}

func render(code, summary, explanation, bad, good, severity string, defaultEnabled bool) string {
	enablement := fmt.Sprintf(
		"This extended rule runs when selected with `--only %s`, enabled in `strider.toml`, or included with `--all-rules`.",
		code,
	)
	if defaultEnabled {
		enablement = "This rule is enabled in Strider's default lint profile."
	}
	return fmt.Sprintf(`---
title: %s
description: %q
---

%s

%s

## Bad

`+"```go"+`
%s
`+"```"+`

## Good

`+"```go"+`
%s
`+"```"+`

## Enable

%s The default severity is `+"`%s`"+`.
`, code, prose(summary), generatedMarker, prose(explanation), strings.TrimSpace(bad), strings.TrimSpace(good), enablement, severity)
}

func prose(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return value
	}
	value = strings.ToUpper(value[:1]) + value[1:]
	if !strings.HasSuffix(value, ".") {
		value += "."
	}
	return value
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate lint docs:", err)
	os.Exit(1)
}
