// Command generate-check-docs renders generated syntax-check pages and keeps
// the default-severity indicator on every check reference page in sync with code.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/gempir/strider/internal/checks"
	"github.com/gempir/strider/internal/checks/syntax/rules"
	"github.com/gempir/strider/internal/diagnostic"
)

const (
	generatedMarker       = "<!-- Code generated by docs/scripts/generate-check-docs.go; DO NOT EDIT. -->"
	oldGeneratedMarker    = "<!-- Code generated by docs/scripts/generate-lint-docs.go; DO NOT EDIT. -->"
	legacyBoilerplate     = "Strider implements this rule natively in its shared lossless Go CST traversal."
	defaultSeverityPrefix = "**Default severity:**"
)

func main() {
	docsDirectory := docsDirectory()
	generateSyntaxPages(docsDirectory)
	synchronizeSeverityBadges(docsDirectory)
}

func generateSyntaxPages(docsDirectory string) {
	all, err := rules.Select(nil)
	if err != nil {
		fatal(err)
	}
	sort.Slice(all, func(i, j int) bool {
		return all[i].Meta().Code < all[j].Meta().Code
	})

	directory := filepath.Join(docsDirectory, "lints")
	for _, rule := range all {
		meta := rule.Meta()
		if strings.TrimSpace(meta.GoodExample) == "" || strings.TrimSpace(meta.BadExample) == "" {
			fatal(fmt.Errorf("syntax check %s has incomplete examples", meta.Code))
		}
		path := filepath.Join(directory, meta.Code+".md")
		current, readErr := os.ReadFile(path)
		if readErr != nil && !os.IsNotExist(readErr) {
			fatal(readErr)
		}
		if readErr == nil && !generatedPage(string(current)) {
			continue
		}
		content := render(
			pageData{code: meta.Code, summary: meta.Summary, explanation: meta.Explanation, bad: meta.BadExample, good: meta.GoodExample, severity: meta.DefaultSeverity},
		)
		if string(current) == content {
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fatal(err)
		}
	}
}

func docsDirectory() string {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal(fmt.Errorf("locate generator source"))
	}
	return filepath.Join(filepath.Dir(sourceFile), "..", "src", "content", "docs")
}

func generatedPage(contents string) bool {
	return strings.Contains(contents, generatedMarker) || strings.Contains(contents, oldGeneratedMarker) || strings.Contains(contents, legacyBoilerplate)
}

type pageData struct {
	code        string
	summary     string
	explanation string
	bad         string
	good        string
	severity    diagnostic.Severity
}

func render(page pageData) string {
	content := fmt.Sprintf(
		`---
title: %s
description: %q
sidebar:
  badge:
    text: %s
    class: severity-indicator severity-%s
---

%s

%s %s `+"`%s`"+`

%s

## Bad

`+"```go"+`
%s
`+"```"+`

## Good

`+"```go"+`
%s
`+"```"+`
`,
		page.code,
		prose(page.summary),
		page.severity,
		page.severity,
		generatedMarker,
		defaultSeverityPrefix,
		severityIndicator(page.severity),
		page.severity,
		prose(page.explanation),
		strings.TrimSpace(page.bad),
		strings.TrimSpace(page.good),
	)
	if page.code == "banned-characters" {
		content += `
## Configuration

Set ` + "`characters`" + ` to the Unicode characters that identifiers must not
contain. Each entry must contain exactly one character. The configured list
replaces the defaults.

` + "```toml" + `
[checks.rules.banned-characters]
characters = ["ᐸ", "ᐳ", "_"]
` + "```" + `

By default, Strider bans ` + "`ᐸ`" + ` (` + "`U+1438 CANADIAN SYLLABICS PA`" + `) and
` + "`ᐳ`" + ` (` + "`U+1433 CANADIAN SYLLABICS PO`" + `). Set ` + "`characters = []`" + ` to
allow every character.
`
	}
	return content
}

func synchronizeSeverityBadges(docsDirectory string) {
	registry, err := checks.NewRegistry(checks.RegistryOptions{MinimumSeverity: diagnostic.SeverityNone})
	if err != nil {
		fatal(err)
	}
	for _, rule := range registry.Rules() {
		meta := rule.Meta()
		path := checkPagePath(docsDirectory, meta)
		contents, readErr := os.ReadFile(path)
		if readErr != nil {
			fatal(fmt.Errorf("check %s documentation: %w", meta.Code, readErr))
		}
		updated := withSeverityMetadata(string(contents), meta.DefaultSeverity)
		if updated != string(contents) {
			if writeErr := os.WriteFile(path, []byte(updated), 0o644); writeErr != nil {
				fatal(writeErr)
			}
		}
	}
}

func checkPagePath(docsDirectory string, meta checks.Meta) string {
	if meta.Code == "format" {
		return filepath.Join(docsDirectory, "formatter.md")
	}
	category := "lints"
	if meta.Capabilities&checks.CapabilityAST != 0 {
		category = "analyzers"
	}
	return filepath.Join(docsDirectory, category, meta.Code+".md")
}

func withSeverityMetadata(contents string, severity diagnostic.Severity) string {
	contents = withSidebarSeverity(contents, severity)
	badge := fmt.Sprintf("%s %s `%s`", defaultSeverityPrefix, severityIndicator(severity), severity)
	lines := strings.Split(contents, "\n")
	for index, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), defaultSeverityPrefix) {
			lines[index] = badge
			if index+1 < len(lines) && strings.TrimSpace(lines[index+1]) != "" {
				lines = append(lines[:index+1], append([]string{""}, lines[index+1:]...)...)
			}
			return strings.Join(lines, "\n")
		}
	}
	frontmatterEnd := -1
	for index := 1; index < len(lines); index++ {
		if strings.TrimSpace(lines[index]) == "---" {
			frontmatterEnd = index
			break
		}
	}
	if frontmatterEnd < 0 {
		fatal(fmt.Errorf("documentation page has no frontmatter"))
	}
	insertAt := frontmatterEnd + 1
	addition := []string{"", badge}
	lines = append(lines[:insertAt], append(addition, lines[insertAt:]...)...)
	return strings.Join(lines, "\n")
}

func withSidebarSeverity(contents string, severity diagnostic.Severity) string {
	lines := strings.Split(contents, "\n")
	frontmatterEnd := -1
	for index := 1; index < len(lines); index++ {
		if strings.TrimSpace(lines[index]) == "---" {
			frontmatterEnd = index
			break
		}
	}
	if frontmatterEnd < 0 {
		fatal(fmt.Errorf("documentation page has no frontmatter"))
	}
	for index := 0; index < frontmatterEnd; index++ {
		if strings.Contains(lines[index], "class: severity-indicator") {
			if index == 0 || !strings.Contains(lines[index-1], "text:") {
				fatal(fmt.Errorf("severity sidebar badge has no text"))
			}
			lines[index-1] = fmt.Sprintf("    text: %s", severity)
			lines[index] = fmt.Sprintf("    class: severity-indicator severity-%s", severity)
			return strings.Join(lines, "\n")
		}
	}
	metadata := []string{"sidebar:", "  badge:", fmt.Sprintf("    text: %s", severity), fmt.Sprintf("    class: severity-indicator severity-%s", severity)}
	lines = append(lines[:frontmatterEnd], append(metadata, lines[frontmatterEnd:]...)...)
	return strings.Join(lines, "\n")
}

func severityIndicator(severity diagnostic.Severity) string {
	return fmt.Sprintf(`<span class="severity-indicator severity-%s" aria-hidden="true"></span>`, severity)
}

func prose(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return value
	}
	value = strings.ToUpper(value[:1]) + value[1:]
	if !strings.HasSuffix(value, ".") {
		value += "."
	}
	return value
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate check docs:", err)
	os.Exit(1)
}
