// Command generate-check-docs renders generated syntax-check pages and keeps
// every check reference page aligned with the registry, examples, configuration,
// and default severity.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/gempir/strider/internal/checks"
	"github.com/gempir/strider/internal/checks/catalog"
	"github.com/gempir/strider/internal/checks/syntax"
	"github.com/gempir/strider/internal/diagnostic"
)

const (
	generatedMarker       = "<!-- Code generated by docs/scripts/generate-check-docs.go; DO NOT EDIT. -->"
	oldGeneratedMarker    = "<!-- Code generated by docs/scripts/generate-lint-docs.go; DO NOT EDIT. -->"
	legacyBoilerplate     = "Strider implements this rule natively in its shared lossless Go CST traversal."
	defaultSeverityPrefix = "**Default severity:**"
)

type pageData struct {
	code        string
	summary     string
	explanation string
	bad         string
	good        string
	severity    diagnostic.Severity
}

func main() {
	docsDirectory := docsDirectory()
	generateSyntaxPages(docsDirectory)
	registry := synchronizeCheckPages(docsDirectory)
	generateCatalogStats(docsDirectory, registry)
	validateCheckPages(docsDirectory, registry)
	validateBehaviorConfiguration(docsDirectory, registry)
}

func generateCatalogStats(docsDirectory string, registry *checks.Registry) {
	stats := struct {
		Checks int `json:"checks"`
	}{
		Checks: len(registry.Checks()),
	}
	contents, err := json.MarshalIndent(stats, "", "  ")
	if err != nil {
		fatal(err)
	}
	contents = append(contents, '\n')
	path := filepath.Join(docsDirectory, "..", "..", "generated", "catalog.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fatal(err)
	}
	current, err := os.ReadFile(path)
	if err == nil && string(current) == string(contents) {
		return
	}
	if err != nil && !os.IsNotExist(err) {
		fatal(err)
	}
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		fatal(err)
	}
}

func generateSyntaxPages(docsDirectory string) {
	all := syntax.Catalog()
	sort.Slice(all, func(i, j int) bool {
		return all[i].Meta().Code < all[j].Meta().Code
	})

	directory := filepath.Join(docsDirectory, "lints")
	for _, rule := range all {
		meta := rule.Meta()
		if strings.TrimSpace(meta.GoodExample) == "" || strings.TrimSpace(meta.BadExample) == "" {
			fatal(fmt.Errorf("syntax check %s has incomplete examples", meta.Code))
		}
		path := filepath.Join(directory, meta.Code+".md")
		current, readErr := os.ReadFile(path)
		if readErr != nil && !os.IsNotExist(readErr) {
			fatal(readErr)
		}
		if readErr == nil && !generatedPage(string(current)) {
			continue
		}
		content := render(
			pageData{
				code:        meta.Code,
				summary:     meta.Summary,
				explanation: meta.Explanation,
				bad:         meta.BadExample,
				good:        meta.GoodExample,
				severity:    meta.DefaultSeverity,
			},
		)
		if string(current) == content {
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fatal(err)
		}
	}
}

func docsDirectory() string {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal(fmt.Errorf("locate generator source"))
	}
	return filepath.Join(filepath.Dir(sourceFile), "..", "src", "content", "docs")
}

func generatedPage(contents string) bool {
	return strings.Contains(contents, generatedMarker) || strings.Contains(contents, oldGeneratedMarker) || strings.Contains(contents, legacyBoilerplate)
}

func render(page pageData) string {
	content := fmt.Sprintf(
		`---
title: %s
description: %q
sidebar:
  badge:
    text: %s
    class: severity-indicator severity-%s
---

%s

%s %s `+"`%s`"+`

%s

## Bad

`+"```go"+`
%s
`+"```"+`

## Good

`+"```go"+`
%s
`+"```"+`
`,
		page.code,
		prose(page.summary),
		page.severity,
		page.severity,
		generatedMarker,
		defaultSeverityPrefix,
		severityIndicator(page.severity),
		page.severity,
		prose(page.explanation),
		strings.TrimSpace(page.bad),
		strings.TrimSpace(page.good),
	)
	return content
}

func synchronizeCheckPages(docsDirectory string) *checks.Registry {
	registry, err := checks.NewRegistry(checks.RegistryOptions{
		MinimumSeverity: diagnostic.SeverityNone,
	})
	if err != nil {
		fatal(err)
	}
	for _, rule := range registry.Checks() {
		meta := rule.Meta()
		path := checkPagePath(docsDirectory, rule)
		contents, readErr := os.ReadFile(path)
		if readErr != nil {
			fatal(fmt.Errorf("check %s documentation: %w", meta.Code, readErr))
		}
		updated := withSeverityMetadata(string(contents), meta.DefaultSeverity)
		updated = withExamples(updated, meta)
		updated = withOptionDocumentation(updated, meta)
		if updated != string(contents) {
			if writeErr := os.WriteFile(path, []byte(updated), 0o644); writeErr != nil {
				fatal(writeErr)
			}
		}
	}
	return registry
}

func withExamples(contents string, meta checks.Meta) string {
	if meta.Code == "format" {
		return contents
	}
	bad := strings.Contains(contents, "\n## Bad\n")
	good := strings.Contains(contents, "\n## Good\n")
	if bad && good {
		return contents
	}
	if strings.TrimSpace(meta.BadExample) == "" || strings.TrimSpace(meta.GoodExample) == "" {
		fatal(fmt.Errorf("check %s has incomplete examples", meta.Code))
	}
	if strings.TrimSpace(meta.BadExample) == strings.TrimSpace(meta.GoodExample) {
		fatal(fmt.Errorf("check %s has identical good and bad examples", meta.Code))
	}
	sections := renderExampleSections(meta.BadExample, meta.GoodExample)
	if !bad && !good {
		if start, end, ok := firstGoCodeBlock(contents); ok {
			remainder := strings.TrimLeft(contents[end:], "\n")
			if remainder != "" {
				remainder = "\n" + remainder
			}
			return strings.TrimRight(contents[:start], "\n") + "\n\n" + sections + remainder
		}
	}
	missing := ""
	if !bad {
		missing += renderBadSection(meta.BadExample)
	}
	if !good {
		missing += renderGoodSection(meta.GoodExample)
	}
	return strings.TrimRight(contents, "\n") + "\n\n" + missing
}

func renderExampleSections(bad, good string) string {
	return renderBadSection(bad) + renderGoodSection(good)
}

func renderBadSection(example string) string {
	return "## Bad\n\n```go\n" + strings.TrimSpace(example) + "\n```\n\n"
}

func renderGoodSection(example string) string {
	return "## Good\n\n```go\n" + strings.TrimSpace(example) + "\n```\n"
}

func firstGoCodeBlock(contents string) (int, int, bool) {
	start := strings.Index(contents, "```go\n")
	if start < 0 {
		return 0, 0, false
	}
	closing := strings.Index(contents[start+len("```go\n"):], "\n```")
	if closing < 0 {
		fatal(fmt.Errorf("documentation page has an unterminated Go code block"))
	}
	end := start + len("```go\n") + closing + len("\n```")
	return start, end, true
}

func validateCheckPages(docsDirectory string, registry *checks.Registry) {
	expected := make(map[string]bool, len(registry.Checks())-1)
	for _, rule := range registry.Checks() {
		meta := rule.Meta()
		path := checkPagePath(docsDirectory, rule)
		contents, err := os.ReadFile(path)
		if err != nil {
			fatal(fmt.Errorf("check %s documentation: %w", meta.Code, err))
		}
		if meta.Code != "format" {
			expected[filepath.Clean(path)] = true
		}
		bad := documentedGoExample(string(contents), "Bad")
		good := documentedGoExample(string(contents), "Good")
		if bad == "" || good == "" {
			fatal(fmt.Errorf("check %s documentation must have non-empty Bad and Good Go examples", meta.Code))
		}
		if bad == good {
			fatal(fmt.Errorf("check %s documentation has identical Bad and Good examples", meta.Code))
		}
	}
	for _, category := range []string{
		"lints",
		"analyzers",
	} {
		directory := filepath.Join(docsDirectory, category)
		entries, err := os.ReadDir(directory)
		if err != nil {
			fatal(err)
		}
		for _, entry := range entries {
			if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
				continue
			}
			path := filepath.Clean(filepath.Join(directory, entry.Name()))
			if !expected[path] {
				fatal(fmt.Errorf("orphan check documentation page %s", path))
			}
		}
	}
}

func documentedGoExample(contents, heading string) string {
	section := strings.Index(contents, "\n## "+heading+"\n")
	if section < 0 {
		return ""
	}
	contents = contents[section:]
	start := strings.Index(contents, "```go\n")
	if start < 0 {
		return ""
	}
	contents = contents[start+len("```go\n"):]
	end := strings.Index(contents, "\n```")
	if end < 0 {
		return ""
	}
	example := strings.TrimSpace(contents[:end])
	if nextHeading := strings.Index(example, "\n## "); nextHeading >= 0 {
		return ""
	}
	return example
}

func validateBehaviorConfiguration(docsDirectory string, registry *checks.Registry) {
	for _, rule := range registry.Checks() {
		meta := rule.Meta()
		if len(meta.Options) == 0 {
			continue
		}
		contents, err := os.ReadFile(checkPagePath(docsDirectory, rule))
		if err != nil {
			fatal(err)
		}
		page := string(contents)
		wantedTokens := []string{
			"## Configuration",
			"[checks." + meta.Code + "]",
		}
		for _, option := range meta.Options {
			wantedTokens = append(wantedTokens, option.Name, option.Help, renderOptionDefault(option))
		}
		for _, wanted := range wantedTokens {
			if !strings.Contains(page, wanted) {
				fatal(fmt.Errorf("check %s documentation is missing configuration token %q", meta.Code, wanted))
			}
		}
	}
}

func checkPagePath(docsDirectory string, descriptor checks.Descriptor) string {
	meta := descriptor.Meta()
	if meta.Code == "format" {
		return filepath.Join(docsDirectory, "formatter.md")
	}
	category := "lints"
	if descriptor.Engine() == checks.EngineSemantic {
		category = "analyzers"
	}
	return filepath.Join(docsDirectory, category, meta.Code+".md")
}

func withOptionDocumentation(contents string, meta checks.Meta) string {
	if len(meta.Options) == 0 {
		return contents
	}
	section := renderOptionDocumentation(meta)
	start := strings.Index(contents, "\n## Configuration\n")
	if start < 0 {
		return strings.TrimRight(contents, "\n") + "\n\n" + section
	}
	start++
	end := strings.Index(contents[start+1:], "\n## ")
	if end < 0 {
		return strings.TrimRight(contents[:start], "\n") + "\n\n" + section
	}
	end += start + 1
	return strings.TrimRight(contents[:start], "\n") + "\n\n" + section + "\n" + strings.TrimLeft(contents[end:], "\n")
}

func renderOptionDocumentation(meta checks.Meta) string {
	var result strings.Builder
	fmt.Fprintf(&result, "## Configuration\n\n")
	fmt.Fprintf(&result, "| Option | Type | Default | Description |\n")
	fmt.Fprintf(&result, "| --- | --- | --- | --- |\n")
	for _, option := range meta.Options {
		fmt.Fprintf(&result, "| `%s` | `%s` | `%s` | %s |\n", option.Name, option.Kind, renderOptionDefault(option), option.Help)
	}
	fmt.Fprintf(&result, "\n```toml\n[checks.%s]\n", meta.Code)
	for _, option := range meta.Options {
		fmt.Fprintf(&result, "%s = %s\n", option.Name, renderOptionDefault(option))
	}
	fmt.Fprintf(&result, "```\n")
	return result.String()
}

func renderOptionDefault(option catalog.OptionSpec) string {
	switch option.Kind {
	case catalog.OptionInt:
		return strconv.Itoa(option.DefaultInt)
	case catalog.OptionStrings:
		if option.DefaultStrings == nil {
			return "[]"
		}
		encoded, err := json.Marshal(option.DefaultStrings)
		if err != nil {
			fatal(err)
		}
		return string(encoded)
	default:
		fatal(fmt.Errorf("unsupported option kind %q", option.Kind))
		return ""
	}
}

func withSeverityMetadata(contents string, severity diagnostic.Severity) string {
	contents = withSidebarSeverity(contents, severity)
	badge := fmt.Sprintf("%s %s `%s`", defaultSeverityPrefix, severityIndicator(severity), severity)
	lines := strings.Split(contents, "\n")
	for index, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), defaultSeverityPrefix) {
			lines[index] = badge
			if index+1 < len(lines) && strings.TrimSpace(lines[index+1]) != "" {
				lines = append(lines[:index+1], append([]string{
					"",
				}, lines[index+1:]...)...)
			}
			return strings.Join(lines, "\n")
		}
	}
	frontmatterEnd := -1
	for index := 1; index < len(lines); index++ {
		if strings.TrimSpace(lines[index]) == "---" {
			frontmatterEnd = index
			break
		}
	}
	if frontmatterEnd < 0 {
		fatal(fmt.Errorf("documentation page has no frontmatter"))
	}
	insertAt := frontmatterEnd + 1
	addition := []string{
		"",
		badge,
	}
	lines = append(lines[:insertAt], append(addition, lines[insertAt:]...)...)
	return strings.Join(lines, "\n")
}

func withSidebarSeverity(contents string, severity diagnostic.Severity) string {
	lines := strings.Split(contents, "\n")
	frontmatterEnd := -1
	for index := 1; index < len(lines); index++ {
		if strings.TrimSpace(lines[index]) == "---" {
			frontmatterEnd = index
			break
		}
	}
	if frontmatterEnd < 0 {
		fatal(fmt.Errorf("documentation page has no frontmatter"))
	}
	for index := 0; index < frontmatterEnd; index++ {
		if strings.Contains(lines[index], "class: severity-indicator") {
			if index == 0 || !strings.Contains(lines[index-1], "text:") {
				fatal(fmt.Errorf("severity sidebar badge has no text"))
			}
			lines[index-1] = fmt.Sprintf("    text: %s", severity)
			lines[index] = fmt.Sprintf("    class: severity-indicator severity-%s", severity)
			return strings.Join(lines, "\n")
		}
	}
	metadata := []string{
		"sidebar:",
		"  badge:",
		fmt.Sprintf("    text: %s", severity),
		fmt.Sprintf("    class: severity-indicator severity-%s", severity),
	}
	lines = append(lines[:frontmatterEnd], append(metadata, lines[frontmatterEnd:]...)...)
	return strings.Join(lines, "\n")
}

func severityIndicator(severity diagnostic.Severity) string {
	return fmt.Sprintf(`<span class="severity-indicator severity-%s" aria-hidden="true"></span>`, severity)
}

func prose(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return value
	}
	value = strings.ToUpper(value[:1]) + value[1:]
	if !strings.HasSuffix(value, ".") {
		value += "."
	}
	return value
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate check docs:", err)
	os.Exit(1)
}
