// Command checkscaffold creates the two files authored for a new check and
// updates generated registration, inventory, golden, and documentation files.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/gempir/strider/internal/checks/catalog"
	"github.com/gempir/strider/internal/diagnostic"
)

const generatedDocsMarker = "<!-- Code generated by scripts/checkscaffold; edit metadata in the check descriptor. -->"

var checkCodePattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:-[a-z0-9]+)+$`)

type scaffoldOptions struct {
	root        string
	engine      string
	code        string
	summary     string
	explanation string
	goodExample string
	badExample  string
	severity    diagnostic.Severity
	stage       string
	optionJSON  string
}

type optionInput struct {
	Name           string   `json:"name"`
	Kind           string   `json:"kind"`
	DefaultInt     int      `json:"default_int,omitempty"`
	DefaultStrings []string `json:"default_strings,omitempty"`
	Help           string   `json:"help"`
}

type scaffoldPlan struct {
	options            scaffoldOptions
	meta               catalog.Meta
	implementationPath string
	testPath           string
	docsPath           string
	registryPath       string
	registrySource     []byte
	implementation     []byte
	test               []byte
	docs               []byte
}

type artifactUpdater func(string) error

func main() {
	options := scaffoldOptions{}
	severity := ""
	flag.StringVar(&options.root, "root", ".", "repository root")
	flag.StringVar(&options.engine, "engine", "", "check engine: syntax or semantic")
	flag.StringVar(&options.code, "code", "", "descriptive kebab-case check code")
	flag.StringVar(&options.summary, "summary", "", "short imperative summary")
	flag.StringVar(&options.explanation, "explanation", "", "signal rationale and false-positive boundary")
	flag.StringVar(&options.goodExample, "good", "", "good Go example")
	flag.StringVar(&options.badExample, "bad", "", "bad Go example")
	flag.StringVar(&severity, "severity", "warning", "default severity: note, warning, or error")
	flag.StringVar(&options.stage, "stage", "types", "semantic stage: types or ssa")
	flag.StringVar(&options.optionJSON, "options-json", "", "optional JSON array of non-negative int or string-list option schemas")
	flag.Parse()
	options.severity = diagnostic.Severity(severity)

	created, err := scaffold(options, updateArtifacts)
	if err != nil {
		fmt.Fprintln(os.Stderr, "checkscaffold:", err)
		os.Exit(1)
	}
	for _, path := range created {
		if _, err := fmt.Fprintln(os.Stdout, path); err != nil {
			fmt.Fprintln(os.Stderr, "checkscaffold:", err)
			os.Exit(1)
		}
	}
}

func scaffold(options scaffoldOptions, update artifactUpdater) ([]string, error) {
	plan, err := prepareScaffold(options)
	if err != nil {
		return nil, err
	}
	writes := []struct {
		path    string
		content []byte
	}{
		{
			path:    plan.registryPath,
			content: plan.registrySource,
		},
		{
			path:    plan.implementationPath,
			content: plan.implementation,
		},
		{
			path:    plan.testPath,
			content: plan.test,
		},
		{
			path:    plan.docsPath,
			content: plan.docs,
		},
	}
	for _, write := range writes {
		if err := os.WriteFile(write.path, write.content, 0o644); err != nil {
			return nil, fmt.Errorf("write %s: %w", relativePath(plan.options.root, write.path), err)
		}
	}
	if update != nil {
		if err := update(plan.options.root); err != nil {
			return nil, fmt.Errorf("scaffold files were written but generated artifact update failed: %w", err)
		}
	}
	return []string{
		relativePath(plan.options.root, plan.implementationPath),
		relativePath(plan.options.root, plan.testPath),
		relativePath(plan.options.root, plan.registryPath),
		relativePath(plan.options.root, plan.docsPath),
	}, nil
}

func prepareScaffold(options scaffoldOptions) (scaffoldPlan, error) {
	root, err := filepath.Abs(options.root)
	if err != nil {
		return scaffoldPlan{}, err
	}
	options.root = root
	options.engine = strings.ToLower(strings.TrimSpace(options.engine))
	options.code = strings.ToLower(strings.TrimSpace(options.code))
	options.summary = strings.TrimSpace(options.summary)
	options.explanation = strings.TrimSpace(options.explanation)
	options.goodExample = strings.TrimSpace(options.goodExample)
	options.badExample = strings.TrimSpace(options.badExample)
	options.stage = strings.ToLower(strings.TrimSpace(options.stage))

	if options.engine != "syntax" && options.engine != "semantic" {
		return scaffoldPlan{}, fmt.Errorf("engine must be syntax or semantic")
	}
	if !checkCodePattern.MatchString(options.code) {
		return scaffoldPlan{}, fmt.Errorf("code must be descriptive kebab-case with at least two words")
	}
	if options.summary == "" || options.explanation == "" || options.goodExample == "" || options.badExample == "" {
		return scaffoldPlan{}, fmt.Errorf("summary, explanation, good, and bad metadata are required")
	}
	if sameProse(options.summary, options.explanation) {
		return scaffoldPlan{}, fmt.Errorf("explanation must add a signal rationale beyond the summary")
	}
	if options.goodExample == options.badExample {
		return scaffoldPlan{}, fmt.Errorf("good and bad examples must differ")
	}
	if options.severity != diagnostic.SeverityNote && options.severity != diagnostic.SeverityWarning && options.severity != diagnostic.SeverityError {
		return scaffoldPlan{}, fmt.Errorf("severity must be note, warning, or error")
	}
	if options.engine == "semantic" && options.stage != "types" && options.stage != "ssa" {
		return scaffoldPlan{}, fmt.Errorf("semantic stage must be types or ssa")
	}
	if options.engine == "syntax" && options.stage != "" && options.stage != "types" {
		return scaffoldPlan{}, fmt.Errorf("stage applies only to semantic checks")
	}
	optionSpecs, optionInputs, err := parseOptions(options.optionJSON)
	if err != nil {
		return scaffoldPlan{}, err
	}
	meta := catalog.Meta{
		Code:            options.code,
		Summary:         options.summary,
		Explanation:     options.explanation,
		GoodExample:     options.goodExample,
		BadExample:      options.badExample,
		DefaultSeverity: options.severity,
		Options:         optionSpecs,
	}
	if err := catalog.ValidateSchema(meta); err != nil {
		return scaffoldPlan{}, fmt.Errorf("option schema: %w", err)
	}
	if err := rejectCodeCollision(root, options.code); err != nil {
		return scaffoldPlan{}, err
	}

	filename := strings.ReplaceAll(options.code, "-", "_")
	implementationPath := filepath.Join(root, "internal", "checks", options.engine, filename+".go")
	testPath := filepath.Join(root, "internal", "checks", options.engine, filename+"_test.go")
	category := "lints"
	registryPath := filepath.Join(root, "internal", "checks", "syntax", "catalog.go")
	if options.engine == "semantic" {
		category = "analyzers"
		registryPath = filepath.Join(root, "internal", "checks", "semantic", "registry.go")
	}
	docsDirectory := filepath.Join(root, "docs", "src", "content", "docs", category)
	docsPath := filepath.Join(docsDirectory, options.code+".md")
	for _, path := range []string{
		implementationPath,
		testPath,
		docsPath,
	} {
		if info, statErr := os.Stat(path); statErr == nil {
			kind := "file"
			if info.IsDir() {
				kind = "directory"
			}
			return scaffoldPlan{}, fmt.Errorf("refusing to replace existing %s %s", kind, relativePath(root, path))
		} else if !errors.Is(statErr, fs.ErrNotExist) {
			return scaffoldPlan{}, fmt.Errorf("inspect %s: %w", relativePath(root, path), statErr)
		}
	}
	if info, statErr := os.Stat(docsDirectory); statErr != nil || !info.IsDir() {
		if statErr == nil {
			statErr = fmt.Errorf("not a directory")
		}
		return scaffoldPlan{}, fmt.Errorf("documentation directory %s is unavailable: %w", relativePath(root, docsDirectory), statErr)
	}
	registrySource, err := os.ReadFile(registryPath)
	if err != nil {
		return scaffoldPlan{}, fmt.Errorf("read registration source: %w", err)
	}
	registration := renderRegistration(options, meta, optionInputs)
	registrySource, err = insertRegistration(registrySource, options.engine, registration)
	if err != nil {
		return scaffoldPlan{}, err
	}
	implementation, test, err := renderAuthoredFiles(options, meta, optionInputs)
	if err != nil {
		return scaffoldPlan{}, err
	}
	return scaffoldPlan{
		options:            options,
		meta:               meta,
		implementationPath: implementationPath,
		testPath:           testPath,
		docsPath:           docsPath,
		registryPath:       registryPath,
		registrySource:     registrySource,
		implementation:     implementation,
		test:               test,
		docs:               renderDocs(meta),
	}, nil
}

func parseOptions(encoded string) ([]catalog.OptionSpec, []optionInput, error) {
	if strings.TrimSpace(encoded) == "" {
		return nil, nil, nil
	}
	decoder := json.NewDecoder(strings.NewReader(encoded))
	decoder.DisallowUnknownFields()
	var inputs []optionInput
	if err := decoder.Decode(&inputs); err != nil {
		return nil, nil, fmt.Errorf("options-json: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			err = fmt.Errorf("multiple JSON values")
		}
		return nil, nil, fmt.Errorf("options-json: %w", err)
	}
	specs := make([]catalog.OptionSpec, 0, len(inputs))
	for _, input := range inputs {
		switch input.Kind {
		case "int":
			specs = append(specs, catalog.NonNegativeIntOption(input.Name, input.DefaultInt, input.Help))
		case "strings":
			specs = append(specs, catalog.StringListOption(input.Name, input.DefaultStrings, input.Help))
		default:
			return nil, nil, fmt.Errorf("option %q kind must be int or strings", input.Name)
		}
	}
	return specs, inputs, nil
}

func rejectCodeCollision(root, wanted string) error {
	codes := map[string]string{
		"format": "format",
	}
	checkRoot := filepath.Join(root, "internal", "checks")
	codeField := regexp.MustCompile(`Code:\s*"([^"]+)"`)
	err := filepath.WalkDir(
		checkRoot,
		func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
				return nil
			}
			contents, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			for _, match := range codeField.FindAllSubmatch(contents, -1) {
				code := string(match[1])
				codes[strings.ToLower(code)] = code
			}
			return nil
		},
	)
	if err != nil {
		return fmt.Errorf("scan existing check codes: %w", err)
	}
	if existing, collision := codes[strings.ToLower(wanted)]; collision {
		return fmt.Errorf("check code %q collides case-insensitively with %q", wanted, existing)
	}
	return nil
}

func renderRegistration(options scaffoldOptions, meta catalog.Meta, inputs []optionInput) string {
	name := goName(options.code)
	if options.engine == "semantic" {
		constructor := "typeCheck"
		if options.stage == "ssa" {
			constructor = "ssaCheck"
		}
		return "\t" + constructor + "(" + name + "Check{}),\n"
	}
	return fmt.Sprintf(
		"\t{\n\t\tbehavior: nodeCheck(nodeSourceFile, (*Pass).check%s),\n\t\tmeta: Meta{\n\t\t\tCode:            %s,\n\t\t\tSummary:         %s,\n\t\t\tExplanation:     %s,\n\t\t\tGoodExample:     %s,\n\t\t\tBadExample:      %s,\n\t\t\tDefaultSeverity: diagnostic.%s,\n%s\t\t},\n\t},\n",
		exportedName(name),
		strconv.Quote(meta.Code),
		strconv.Quote(meta.Summary),
		strconv.Quote(meta.Explanation),
		strconv.Quote(meta.GoodExample),
		strconv.Quote(meta.BadExample),
		severityIdentifier(meta.DefaultSeverity),
		renderCatalogOptionField(inputs),
	)
}

func insertRegistration(source []byte, engine, registration string) ([]byte, error) {
	marker := "\n}\n\n// Catalog returns"
	if engine == "semantic" {
		marker = "\n}\n\n// Plan is"
	}
	index := bytes.Index(source, []byte(marker))
	if index < 0 {
		return nil, fmt.Errorf("registration marker is missing from %s catalog", engine)
	}
	result := make([]byte, 0, len(source)+len(registration))
	result = append(result, source[:index]...)
	result = append(result, '\n')
	result = append(result, registration...)
	result = append(result, source[index+1:]...)
	return result, nil
}

func renderAuthoredFiles(options scaffoldOptions, meta catalog.Meta, inputs []optionInput) ([]byte, []byte, error) {
	name := goName(options.code)
	testName := exportedName(name)
	var implementation string
	var test string
	if options.engine == "semantic" {
		catalogImport := ""
		if len(inputs) != 0 {
			catalogImport = "\n\t\"github.com/gempir/strider/internal/checks/catalog\""
		}
		implementation = fmt.Sprintf(
			`package semantic

import (%s
	"github.com/gempir/strider/internal/diagnostic"
)

type %sCheck struct{}

func (%sCheck) Meta() Meta {
	return Meta{
		Code: %s,
		Summary: %s,
		Explanation: %s,
		GoodExample: %s,
		BadExample: %s,
		DefaultSeverity: diagnostic.%s,
%s	}
}

func (%sCheck) Run(*Pass) {}
`,
			catalogImport,
			name,
			name,
			strconv.Quote(meta.Code),
			strconv.Quote(meta.Summary),
			strconv.Quote(meta.Explanation),
			strconv.Quote(meta.GoodExample),
			strconv.Quote(meta.BadExample),
			severityIdentifier(meta.DefaultSeverity),
			renderOptionField(inputs, "\t\t"),
			name,
		)
		test = fmt.Sprintf(
			`package semantic

import "testing"

func Test%sScaffold(t *testing.T) {
	check := %sCheck{}
	if got, want := check.Meta().Code, %s; got != want {
		t.Fatalf("code = %%q, want %%q", got, want)
	}
}
`,
			testName,
			name,
			strconv.Quote(meta.Code),
		)
	} else {
		implementation = fmt.Sprintf(`package syntax

import "github.com/gempir/strider/internal/cst"

func (*Pass) check%s(*cst.SourceFile) {}
`, testName)
		test = fmt.Sprintf(
			`package syntax

import "testing"

func Test%sScaffold(t *testing.T) {
	for _, check := range Catalog() {
		if check.Meta().Code == %s {
			return
		}
	}
	t.Fatal("scaffolded check is not registered")
}
`,
			testName,
			strconv.Quote(meta.Code),
		)
	}
	formattedImplementation, err := format.Source([]byte(implementation))
	if err != nil {
		return nil, nil, fmt.Errorf("format implementation template: %w", err)
	}
	formattedTest, err := format.Source([]byte(test))
	if err != nil {
		return nil, nil, fmt.Errorf("format test template: %w", err)
	}
	return formattedImplementation, formattedTest, nil
}

func renderOptionField(inputs []optionInput, indent string) string {
	if len(inputs) == 0 {
		return ""
	}
	var result strings.Builder
	result.WriteString(indent)
	result.WriteString("Options: []catalog.Option{\n")
	for _, input := range inputs {
		result.WriteString(indent)
		result.WriteString("\t")
		switch input.Kind {
		case "int":
			fmt.Fprintf(&result, "catalog.NonNegativeIntOption(%s, %d, %s),\n", strconv.Quote(input.Name), input.DefaultInt, strconv.Quote(input.Help))
		case "strings":
			fmt.Fprintf(&result, "catalog.StringListOption(%s, %#v, %s),\n", strconv.Quote(input.Name), input.DefaultStrings, strconv.Quote(input.Help))
		}
	}
	result.WriteString(indent)
	result.WriteString("},\n")
	return result.String()
}

func renderCatalogOptionField(inputs []optionInput) string {
	return renderOptionField(inputs, "\t\t\t")
}

func renderDocs(meta catalog.Meta) []byte {
	return []byte(fmt.Sprintf(
		`---
title: %s
description: %s
sidebar:
  badge:
    text: %s
    class: severity-indicator severity-%s
---

%s

**Default severity:** %s `+"`%s`"+`

%s

## Bad

`+"```go"+`
%s
`+"```"+`

## Good

`+"```go"+`
%s
`+"```"+`
`,
		meta.Code,
		strconv.Quote(meta.Summary),
		meta.DefaultSeverity,
		meta.DefaultSeverity,
		generatedDocsMarker,
		meta.DefaultSeverity,
		meta.DefaultSeverity,
		meta.Explanation,
		meta.BadExample,
		meta.GoodExample,
	))
}

func updateArtifacts(root string) error {
	command := exec.Command("make", "check-update")
	command.Dir = root
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return err
	}
	return nil
}

func severityIdentifier(severity diagnostic.Severity) string {
	switch severity {
	case diagnostic.SeverityNote:
		return "SeverityNote"
	case diagnostic.SeverityWarning:
		return "SeverityWarning"
	case diagnostic.SeverityError:
		return "SeverityError"
	default:
		panic("validated severity")
	}
}

func goName(code string) string {
	parts := strings.Split(code, "-")
	for index := 1; index < len(parts); index++ {
		parts[index] = exportedName(parts[index])
	}
	return strings.Join(parts, "")
}

func exportedName(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToUpper(value[:1]) + value[1:]
}

func sameProse(left, right string) bool {
	normalize := func(value string) string {
		return strings.ToLower(strings.TrimSuffix(strings.TrimSpace(value), "."))
	}
	return normalize(left) == normalize(right)
}

func relativePath(root, path string) string {
	relative, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(relative)
}
